# Generated by Django 2.1.7 on 2019-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='phoneNumber',
            new_name='phoneNum',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
