# Generated by Django 2.1.7 on 2019-03-19 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190319_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\(\\d{3}\\)-\\d{3}-\\d{4}')]),
        ),
    ]
