# Generated by Django 2.1.7 on 2019-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blogcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='benefits',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
