# Generated by Django 2.1.7 on 2019-03-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogpost_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlogPost'),
        ),
    ]
