# Generated by Django 2.1.7 on 2019-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190319_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
