# Generated by Django 2.1.7 on 2019-03-19 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190319_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('companyName', models.TextField()),
                ('salary', models.IntegerField()),
                ('postion', models.TextField()),
                ('benefits', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')])),
                ('streetNum', models.IntegerField()),
                ('streetName', models.TextField()),
                ('townName', models.TextField()),
                ('state', models.TextField(max_length=2)),
                ('zipCode', models.IntegerField()),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
