# Generated by Django 2.1.7 on 2019-03-21 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userblogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBlogPost',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='zipCode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex=' \\d{5}?')]),
        ),
    ]
