# Generated by Django 2.1.7 on 2019-03-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190321_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='zipCode',
        ),
    ]
